### PR TITLE
UnicodeDecodeError fix

### PR DESCRIPTION
**Pull request by eriktelepovsky**
Fixed issue #15

### CODE REVIEW

**Comment by ionelmc** [comment]
Mind updating `changelog/authors.rst`?

**Comment by eriktelepovsky** [comment]
It would be my pleasure. Should I update version in setup.py as well?

**Comment by ionelmc** [comment]
No, that's part of the release process (bumpversion).

**Comment by eriktelepovsky** [comment]
Understood. It's done. Just update release date in changelog once ready.

**Comment by ionelmc** [comment]
Alright, thanks!

**Pull request merged**
