### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by gabn88**
This is a bit neater. Include Django 1.9 support

### CODE REVIEW

**Comment by ionelmc** [comment]
Hey, thanks for the changes. Can you change the code to not use `StrictVersion` at all? It's broken beyond belief (try comparing some beta/rc versions and see how crazy it is).

**Comment by gabn88** [comment]
Is LooseVersion better?

**Comment by ionelmc** [comment]
Everything in distutils is bad :grin:

**Comment by gabn88** [comment]
What do you recommend then? just django.version < 1.8 is going to say that 1.10 is smaller...

**Comment by gabn88** [comment]
maybe django.VERSION < (1,8,0,0,0)?

**Comment by ionelmc** [comment]
Don't do version checks. Just *try/except ImportError: import something else*

I've been burned too many times in the past with version checks. Feature detection is better.

**Comment by gabn88** [comment]
ah, of course :+1: will do a commit :)

**Comment by gabn88** [comment]
Not good enough?

**Comment by ionelmc** [comment]
It's perfect. Just github don't sent me notifications for commits being pushed :disappointed:

**Comment by gabn88** [comment]
Hi ionelmc, do you maybe find some time to update the PyPi repository? Was fixing the same issue I remembered fixing before today ;) Thank you!

**Comment by gabn88** [comment]
By the way, I found that importing the OrderedDict straight from collections is even neater

**Comment by ionelmc** [comment]
@gabn88 isn't 3.0 on pypi including this pr? eg https://pypi.python.org/pypi/django-redisboard/3.0.0

**Comment by gabn88** [comment]
Huh, I runned my automatic update all packages script, but it did not find this update... strange, sorry for the inconvenience!

**Pull request merged**
