### PR TITLE
Django3 Compatibility 

### PR DESCRIPTION
**Pull request by Alireza2n**
Provides replacements/fixes for a couple of Django's removed modules and API in Django 3.

### CODE REVIEW

**Comment by Alireza2n** [comment]
May close #43 .

**Comment by heckad** [comment]
@ionelmc?

**Comment by ionelmc** [comment]
It's on my todolist. I hope to get around to it this weekend.

**Comment by ionelmc** [comment]
It's in master now, now it's only a matter of getting that CI green again.

**Comment by Alireza2n** [comment]
> It's in master now, now it's only a matter of getting that CI green again.

Thanks!
I'll try to fix issues with tests for python3.x.

**Comment by ionelmc** [comment]
Well it's basically passing. I'll get the release out, just have to check that the cli still works.

**Pull request closed without merging**
